name: methylation_preprocessing
channels:
          - r
          - bioconda
          - conda-forge
          - defaults
dependencies:
          - bioconductor-enmix=1.18.0
          - r-broom=0.5.0
